include $(THEOS)/makefiles/common.mk

TWEAK_NAME = YTVideoOverlay
$(TWEAK_NAME)_FRAMEWORKS = UIKit Foundation
$(TWEAK_NAME)_CFLAGS = -fobjc-arc -Wno-unused-function -I../YTLite-5.2b4-fixed
$(TWEAK_NAME)_FILES = Init.x

include $(THEOS_MAKE_PATH)/tweak.mk
